name: my_project
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: 1.0.0
  json_annotation: ^4.8.1
  freezed_annotation: 2.2.0
  uuid: 3.0.7
  get_it: 7.6.0
  logger: 2.0.1
  orm: ^3.4.4


dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

